export const posts = [
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Social media',
		date: '1 seconds ago',
		message: 'Так виглядає головна сторінка.',
		isFollow: true,
		avatarId: 4,
		imageId: 6,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Так виглядає повідомленя поста.',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
	{
		name: 'Vladyslav Kovalevych',
		description: 'Robatics industrial',
		date: '12 seconds ago',
		message: 'Мій перший блог в моїй соціальній мережі',
		isFollow: true,
		avatarId: 4,
		imageId: 5,
	},
	{
		name: 'Dev Ops',
		description:
			'English syllabus. For this type of writing, they get to learn about retrieving and interpreting information',
		date: '1 hr ago',
		message: `When you were not at home, your friend called and informed your sister about the cancellation of a plan for the next day. So, your sister will leave you a message before going out to inform you about your friend’s call.
Messages can be passed through different mediums, be it phones, texts or emails. But for school students, a generic form of message writing is included under the English syllabus. For this type of writing, they get to learn about retrieving and interpreting information through the conversation given. Then, they are taught about writing the basic inputs into a well-drafted format.`,
		isFollow: true,
		avatarId: 3,
		imageId: 3,
	},
	{
		name: 'Julia Robert',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: true,
		avatarId: 2,
		imageId: 1,
	},
	{
		name: 'Mark Stard',
		description: 'Product Designer at lancar.id',
		date: '1 hr ago',
		message: 'Challenge Application about food',
		isFollow: false,
		avatarId: 3,
		imageId: 2,
	},
];
